#!/bin/bash
source setup.sh


#Get the test host
opt1=$1
remote_command=""

OPTIND=1
while getopts "h?:" opt; do
	case "$opt" in
		h|\?)
		echo "Usage: connect <hostname> [command]"
		exit 0
		;;
    esac
done

test_host=$opt1
remote_command=$@

if [ "$test_host" = "" ] ; then
 echo "Please specify a host name"
 echo "Usage: connect <hostname> [command]"
 exit 0
fi

test_ip=`cat $CONFIG_PATH/remotes | grep $test_host$ | awk '{print $1}'`
echo "connecting to $test_host $test_ip"

command=`echo $remote_command | awk '{$1=""; sub(" ", ""); print}'`

if [ "$remote_command" = "$test_host" ] ; then
 ssh -o StrictHostKeyChecking=no -q $ID_OPT $TEST_USER@$test_ip
else
 ssh -o StrictHostKeyChecking=no $ID_OPT $TEST_USER@$test_ip $command
fi
 
