#!/bin/bash
source testenv.sh
#Get the test host
test_host=$1

if [ "$test_host" = "" ] ; then
 echo "Please specify a host name"
 exit 0
fi

test_ip=`cat $TEST_HOME/remotes | grep $test_host$ | awk '{print $1}'`
echo "connecting to $test_ip"
echo

scp $ID_OPT $TEST_FILES $TEST_USER@$test_ip:/home/$TEST_USER

ssh $ID_OPT -R 7000:127.0.0.1:7000 $TEST_USER@$test_ip <<EOF
echo "setting JVM_ARGS=$SERVER_JVM_ARGS"
export JVM_ARGS="$SERVER_JVM_ARGS"
touch jmeter-server.log
./"$JMETER_VERSION"/bin/jmeter-server -Djava.rmi.server.hostname=$test_ip -p jmeter.properties  & tail -f jmeter-server.log
EOF

