#!/bin/bash
source setup.sh
nodes=`cat $CONFIG_PATH/remotes | awk '{print $2}'`

for node in $nodes
do
 $TEST_HOME/connect $node <<EOF
 echo "Downloading $JMETER_VERSION.tgz"
 wget -q http://www.trieuvan.com/apache//jmeter/binaries/"$JMETER_VERSION".tgz
 echo "Updating apt repository"
 sudo apt-get update -y -qq
 echo "Installing java"
 sudo apt-get install openjdk-7-jdk -y -qq
 echo "Extracting jmeter package"
 tar zxf "$JMETER_VERSION".tgz
 rm "$JMETER_VERSION".tgz
EOF
done
