#!/bin/bash
source testenv.sh
nodes=`cat remotes | awk '{print $1}'`

for node in $nodes
do
 ssh -i $TEST_HOME/certs/$JMETER_CERT -R 7000:127.0.0.1:7000 -N $TEST_USER@$node &
 echo $! >> .ssh_worker_pids
done

