#!/bin/bash
source testenv.sh
nodes=`cat remotes | awk '{print $1}'`

killall ssh

for node in $nodes
do
 ssh -q -n -i $TEST_HOME/certs/$JMETER_CERT $TEST_USER@$node killall java
done
echo
echo "Worker nodes stopped."
