#!/bin/bash
source testenv.sh
nodes=`cat remotes | awk '{print $1}'`

pids=`cat .ssh_worker_pids | awk '{print $1}'`
for pid in $pids
do
  kill $pid
done
rm -rf .ssh_worker_pids

for node in $nodes
do
 ssh -q -n -i $TEST_HOME/certs/$JMETER_CERT $TEST_USER@$node killall java
done
echo
echo "Worker nodes stopped."
