#!/bin/bash
source setup.sh
nodes=`cat $CONFIG_PATH/remotes | awk '{print $1}'`

pids=`cat .ssh_worker_pids | awk '{print $1}'`
for pid in $pids
do
  kill $pid
done
rm -rf .ssh_worker_pids

for node in $nodes
do
 ssh -q -n $ID_OPT $TEST_USER@$node killall java
done
echo
echo "Worker nodes stopped."
