#!/bin/bash
source setup.sh

addresses=`cat $CONFIG_PATH/remotes | awk '{print $1}'`
list=""

for address in $addresses
do
 if [ "$list" = "" ] ; then
   list=$address
 else
   list=$list,$address
 fi
done

(cd $CONFIG_PATH; \
cp jmeter.properties jmeter.properties.bak; \
cat jmeter.properties | sed -e "s|^remote_hosts=.*$|remote_hosts=$list|" > jmeter.properties.new; \
cat settings | sed -e "s|^export TEST_REMOTE=.*$|export TEST_REMOTE=$list|" > settings.new; \
mv jmeter.properties.new jmeter.properties; \
mv settings.new settings; \
rm jmeter.properties.bak;)

source setup.sh 
