#!/bin/bash
source testenv.sh
addresses=`cat remotes | awk '{print $1}'`
list=""

for address in $addresses
do
 if [ "$list" = "" ] ; then
   list=$address
 else
   list=$list,$address
 fi
done

cp jmeter.properties jmeter.properties.bak
cat jmeter.properties | sed -e "s|^remote_hosts=.*$|remote_hosts=$list|" > jmeter.properties.new
cat testenv.sh | sed -e "s|^export TEST_REMOTE=.*$|export TEST_REMOTE=$list|" > testenv.sh.new
mv jmeter.properties.new jmeter.properties
mv testenv.sh.new testenv.sh
rm jmeter.properties.bak

source testenv.sh 
